### ISSUE TITLE
Error with Next.js 13

### ISSUE THREAD

**Issue by ansbr** [EthosWallet/ethos-connect#25]
Hello! I try to connect my next.js application with Ethos, but there are some error
`window.navigator.wallets is not an array`

As result I can't connect to sui at all... Maybe it happens with version 13? Can you fix it? 

![image](https://user-images.githubusercontent.com/58120694/221820380-eea9fc97-fad2-44b3-9ce2-2ec52f55aa95.png)

![image](https://user-images.githubusercontent.com/58120694/221820535-21de212d-a5ad-4f2a-8e15-6dd33cd1ea76.png)

**Comment by jaredcosulich** [comment]
Hi, can you share how you are trying to connect to Ethos?
