### ISSUE TITLE
AddressWidget error when trying to exludeButtons

### ISSUE THREAD

**Issue by StefosGeo** [EthosWallet/ethos-connect#26]
I am trying to use the AddressWidget inside my App. I want to exlude the WalletExplorer button so I did this:

`      <ethos.components.AddressWidget excludeButtons={[AddressWidgetButtons.WalletExplorer]} />
`
The problem with this is that:

`ERROR in ./src/client/layouts/NavBar.tsx 40:0-85
Module not found: Error: Package path ./dist/enums/AddressWidgetButtons is not exported from package .../node_modules/ethos-connect (see exports field in .../node_modules/ethos-connect/package.json)
`

So the type need to be used is not properly exported. I tried to use the value directly "wallet_explorer" but the component expects type of `AddressWidgetButtons` , so I need to use ts-ignore.

I am raising this issue for future resolution.

**Comment by jaredcosulich** [comment]
Thank you for reporting this. We'll look into it right away.

**Comment by jaredcosulich** [comment]
Hi,

Can you try this:

```
<ethos.components.AddressWidget excludeButtons={[ethos.enums.AddressWidgetButtons.WalletExplorer]} />
```

**Comment by jaredcosulich** [comment]
I've updated the docs to include this example.
