### ISSUE TITLE
EthosConnectProvider enteres infinite re-render cycle without ethosConfiguration

### ISSUE THREAD

**Issue by ajobi-uhc** [EthosWallet/ethos-connect#27]
When instantiating the provider in a vanilla create-react-app, when the EthosConnectProvider is passed without a ethosConfiguration, the component enters an infinite re-render loop.

**Comment by jaredcosulich** [comment]
Thank you. We'll take a look.

**Comment by jaredcosulich** [comment]
This should be fixed with the latest build.
