### ISSUE TITLE
Why can't I get the `public_key` of my account?

### ISSUE THREAD

**Issue by vladilen11** [EthosWallet/ethos-connect#37]
my code:
```javascript
        console.log(wallet.address)
        console.log(wallet.getAddress())
        console.log(wallet.accounts)
        console.log(wallet.currentAccount)
```
![image](https://user-images.githubusercontent.com/125375292/236540437-e78baa69-8888-4a9d-bd45-f2728456d6c6.png)

**Comment by jaredcosulich** [comment]
We hope to add this in soon, but generally speaking have not found it to be very necessary. What are you trying to use it for?

**Comment by vladilen11** [comment]
verify signature or get pubkey to cal a funcation.

**Comment by jaredcosulich** [comment]
On Sui it's easier to verify a signature using the `verifySignature` function which does not require a public key:

https://github.com/EthosWallet/ethos-example-app/blob/4d37d7e1903d92de55bc19bed24240455c69c60d/components/Sign.tsx#L20

That said, we will get to this soon.
